### ISSUE TITLE
Deleting CRDs lead to dataloss (fortunately on test cluster)

### ISSUE THREAD

**Issue by rbtcollins** [crossplane/provider-azure#215]
### What happened?
We had a cluster that was running the 0.10 azure provider, and I needed to upgrade to 0.15ish. It had 19 CRDs, not the 17 0.15 has, so we removed the azure crossplace specific CRDs in a batch, as there was no time efficient way to determine which kubernetes-api-named CRD matched which kubebuilder-named file on disk.

This then lead to a cascading delete of all the managed resources (but we didn't know about it immediately). What we observed was a stall on the delete, which eventually corrected itself, and being used to Kubernetes and CRDs, we didn't immediately panic.

We then uploaded the new CRDs, uploaded a new deployment object for the provider, and then watched in horror as it reconciled the pending deletes deleting all our databases, accounts etc.

### How can we reproduce it?
The above should be sufficient

### What environment did it happen in?
Crossplane version: 
0.10 + v0.15.0-rc.0-3-g1627754

**Comment by negz** [comment]
Hi @rbtcollins, thanks for raising this issue.

Do I follow correctly that you:

1. Stopped the 0.10 Azure provider (i.e. removed or scaled down its deployment).
2. Deleted all 0.10 Azure CRDs.
3. Installed new 0.15 Azure CRDs
4. Started the 0.15 Azure provider

If so, the behaviour you described is what I would expect - deleting a CRD deletes all of the CRs defined by that CRD. What I suspect happened here is that deleting the CRDs set a deletion timestamp on all of your Azure managed resources - i.e. marked them for deletion. Typically Kubernetes will immediately delete resources once the deletion timestamp is set, but the Crossplane provider adds a finalizer to the resources. The API server waits for this finalizer to be removed before completing the deletion - giving the provider time to potentially delete your external resources correspondingly. In this instance the deletion of the CRDs and their defined CRs would have been blocked because there was no provider running to process the deletes and remove the finalizers. As soon as you deployed the new 0.15 provider it would have seen that all of its resources had deletion timestamps set and thus processed the deletes.

One way to guard against this is to set `deletionPolicy: Orphan` on all of your resources - even as a temporary measure when undertaking potentially risky migrations or maintenance. When this policy is set Crossplane will orphan rather than delete your Azure resources if their corresponding managed resources are deleted.

**Comment by rbtcollins** [comment]
Yes, that was the sequence. Is that deletion of CR's done via `ownerReferences` in the crossplane case, or is it some underlying system behaviour I just haven't encountered before?

We did have external deletion protection in place, but I'm not sure if it was via `deletionPolicy: Orphan` or something else @kornelione can shed light on that. (But whatever it was it wasn't honoured).

**Comment by negz** [comment]
> is it some underlying system behaviour

I believe so. The [CRD documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#delete-a-customresourcedefinition) says:

> When you delete a CustomResourceDefinition, the server will uninstall the RESTful API endpoint **and delete all custom objects stored in it**.

**Comment by muvaf** [comment]
This is expected behavior of CRDs in Kubernetes and there isn't much Crossplane can do to prevent deletion of CRs when CRD is deleted. Feel free to reopen.
