### ISSUE TITLE
Updates to parent can cause deletion of nested child resources

### ISSUE THREAD

**Issue by hasheddan** [crossplane/provider-azure#23]
### What happened?

The Azure Go SDK allows for nesting of child resources in the struct of their parent. For example, the `VirtualNetwork` struct [nests many other resource types](https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2019-07-01/network/models.go) related to networking. For multiple reasons, including the [size limitation](https://github.com/kubernetes/kubernetes/issues/82292) of CRDs, we do not embed child types, such as `Subnet`, into parent resource types, such as `VirtualNetwork`, when the child has its own Crossplane representation as well (i.e. there is a `Subnet` CRD).

### How can we reproduce it?

1. Create a `VirtualNetwork` with no `tags`
2. Create a `Subnet` in that virtual network
3. Add tags to the `VirtualNetwork` in the Azure portal

Because the virtual network has now diverged from the `VirtualNetwork` `spec`, the managed controller will attempt to update the virtual network to match the `spec`. This involves calling [`CreateOrUpdate()`](https://github.com/crossplaneio/stack-azure/blob/a188a1c48a0c0aa80d2cebd18f0318d4177bb2b3/pkg/controller/network/virtualnetwork/managed.go#L157) with an empty slice of subnet references, thus deleting the subnet that currently exists. The `Subnet` managed controller will recreate the subnet once it notices that it has been deleted, but this could have adverse effects on any resource that utilizes that subnet.

### What environment did it happen in?
stack-azure version: https://github.com/crossplaneio/stack-azure/commit/a188a1c48a0c0aa80d2cebd18f0318d4177bb2b3

**Comment by muvaf** [comment]
It seems to me this is not specific to this resource and we need to settle on a generic pattern because we'll probably see a similar case in other resources or even other provider APIs we'd like to support. Even for only this resource, as once you mentioned, the tree of objects you can construct and create/update via CreateOrUpdate call can get _really_ long and span to many resources.

Two solutions I'm seeing can unfold:
* Subnet controller does not interact with Azure API directly, but it only makes changes to the VirtualNetwork CR's Spec's `[]*Subnets` field. Basically using VirtualNetwork CR as its API to communicate with Azure. Once a change happens in Subnet CR, it propagates that to VirtualNetwork CR's spec via a merge patch (add to list or update if the entry already exists). This  allows user both manage/import their Subnets through our Subnet CRs and directly through VirtualNetwork CR.
* Subnet controller works as is. Before each `CreateOrUpdate` call, VirtualNetwork controller scans the Subnet CRs, adds them to its array and do the call. Note that it won't change the VirtualNetwok CR's Spec, it will only include information gathered from a Subnet CR list to the Azure VirtualNetwork object that is sent to Azure API in the controller code. This forces user to specify Subnets only through Subnet CR, meaning no non-Crossplane managed Subnets can be used.

In both of the points above, think of Subnet like just another resource that may or may not exist together with another resource. For example, while one can say Subnet cannot exist without a VirtualNetwork, it can easily be `SecurityGroup` resource which doesn't necessarily need a Subnet/VirtualNetwork but it can actually be included in their `CreateOrUpdate` call and has its own `CreateOrUpdate` call. See `SubnetPropertiesFormat` struct in Azure SDK, it has `NetworkSecurityGroup *SecurityGroup` and `SecurityGroup` object can be an independent or dependent object.

With the questionable knowledge of Azure API I have, none of the options above look very good to me and I am not sure how many resources' endpoints are designed this way. But I think a thorough research on how big the tree can get and how they decide what to include in an object's tree could help us to see the full picture. We might even consider consolidating some resources like remove Subnet CR and controller and have users manage Subnets via VirtualNetwork.

**Comment by muvaf** [comment]
I think we have made the decision about this a while ago.
